services:
  - type: web
    name: backendFlutter
    env: node
    buildCommand: |
      npm install
      apt-get update
      apt-get install -y chromium chromium-sandbox
    startCommand: npm start